# Write the pairwise mixed-model results (summary_table from 05_mixed_models.R)
# to a Markdown report: an overview table per gas (conditions × comparisons,
# significant differences in bold), followed by full results tables per condition.

# row and column order follow the comparison and condition order used in 05
cmp_levels = sapply(comparisons, \(x) paste(x[2], "vs", x[1]))
gas_label  = c(CO2 = "CO₂", CH4 = "CH₄", H2O = "H₂O", N2O = "N₂O", NH3 = "NH₃")
gases      = intersect(names(gas_label), measurements)

# 4 significant figures without scientific notation; p-values below 0.001 in
# scientific notation; significant results bolded and starred
format_num = function(x) format(signif(x, 4), scientific = FALSE, drop0trailing = TRUE, trim = TRUE)
format_p   = function(p) ifelse(p < 0.001, formatC(p, format = "e", digits = 1), sprintf("%.3f", p))
mark_sig   = function(txt, sig) ifelse(sig, paste0("**", txt, "** \\*"), txt)

# overview cell, e.g. "-4.8% (0.011)"; bolded when significant
md_data = summary_table %>%
  mutate(cell = paste0(sprintf("%+.1f%%", percent_change), " (", format_p(p_treatment), ")"),
         cell = if_else(significant, paste0("**", cell, "**"), cell))

md_lines = c(
  "# Pairwise mixed-model results",
  "",
  paste0("Pairwise repeated-measures linear mixed models, fitted separately for each measurement condition × gas × ",
         "treatment comparison (", nrow(md_data), " models). Each model uses only the 8 pots ",
         "(2 treatments × 4 replicates) of its comparison."),
  "",
  "```",
  "gas ~ Treatment * Occasion,  random = ~ 1 | Replicate/PotID,  corCAR1(form = ~ timestamp | Replicate/PotID)",
  "```",
  "",
  "- **Response:** mean concentration per chamber window (`picarro_data_averaged`).",
  "- **Difference** = test − reference, averaged over the 15 measurement occasions. **% change** is relative to the reference mean.",
  paste0("- **p** = Type III F-test for Treatment (3 denominator df in every model). \\* = p < 0.05. ",
         "No correction for multiple testing across the ", nrow(md_data), " models."),
  "- **Interaction p** = Treatment × Occasion: whether the treatment difference changes over time.",
  "",
  "Generated by `scripts/06_write_markdown.R` from the results of `scripts/05_mixed_models.R`.",
  "",
  "## Overview: % change (p)",
  "",
  "% change of the test treatment relative to the reference, with p. **Bold**: p < 0.05.",
  ""
)

# one table per gas: rows are measurement conditions, columns are comparisons
for (g in gases) {
  md_lines = c(md_lines, paste("###", gas_label[g]), "",
               paste0("| Condition | ", paste(cmp_levels, collapse = " | "), " |"),
               paste0("|---|", strrep("---|", length(cmp_levels))))
  for (condition_name in conditions) {
    r = filter(md_data, gas == g, Condition == condition_name)
    cells = sapply(cmp_levels, \(cmp) r$cell[r$comparison == cmp])
    md_lines = c(md_lines, sprintf("| %s | %s |", condition_name, paste(cells, collapse = " | ")))
  }
  md_lines = c(md_lines, "")
}

md_lines = c(md_lines, "## Full results", "")
for (condition_name in conditions) {
  md_lines = c(md_lines, paste("###", condition_name), "",
    "| Gas | Comparison | Reference mean | Test mean | Difference [95% CI] | % change | Direction | p | Interaction p |",
    "|---|---|---|---|---|---|---|---|---|")
  for (g in gases) for (cmp in cmp_levels) {
    r = filter(md_data, Condition == condition_name, gas == g, comparison == cmp)
    md_lines = c(md_lines, sprintf("| %s | %s | %s | %s | %s [%s, %s] | %+.1f%% | %s | %s | %s |",
      gas_label[g], cmp, format_num(r$mean_ref), format_num(r$mean_test),
      format_num(r$difference), format_num(r$CI_lower), format_num(r$CI_upper), r$percent_change,
      r$direction, mark_sig(format_p(r$p_treatment), r$significant), format_p(r$p_interaction)))
  }
  md_lines = c(md_lines, "")
}

writeLines(md_lines, file.path(base, "output/tables/mixed_model_results.md"))
